"""Contrastive corpus for the AMUSEMENT / FUNNINESS emotion vector.

POS = passages that are funny / amusing / evoke laughter.
NEG = passages that are equally VIVID, EMOTIONAL, exclamatory and dialogue-rich
      but NOT funny (anger, fear, sadness, drama, excitement).

The negatives are deliberately style-matched to the positives (exclamation marks,
quoted speech, first-person voice, vivid imagery) so the difference-of-means
direction captures "this is FUNNY" specifically, rather than a surface artefact
like punctuation, arousal, or vividness.  (A first attempt with flat, neutral
office-prose negatives produced a punctuation detector, not an amusement one.)
"""

POS = [
    "And that's when I realized the cat had been wearing my toupee to job interviews this whole time!",
    "He showed up to the funeral in a full inflatable T-rex costume and insisted it was what she would have wanted!",
    "My doctor told me to avoid stress, so I immediately quit being a person and became a houseplant!",
    "The GPS said 'turn left,' so naturally I drove the car directly into a swimming pool, as one does!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised!",
    "Why don't scientists trust atoms? Because they make up absolutely everything!",
    "I bought my kid a fridge for his birthday. I can't wait to see his little face light up when he opens it!",
    "The waiter asked if I wanted my pizza cut into eight slices or twelve. I said eight, I could never eat twelve!",
    "My therapist says I have a preoccupation with vengeance. We'll see about that!",
    "I haven't slept for ten days, because that would be way too long!",
    "A guy walks into a bar, and the bartender says, 'Why the long face?' He says, 'Because I'm a horse, Brenda!'",
    "I tried to catch some fog yesterday. I mist!",
    "My grandfather has the heart of a lion and a lifetime ban from the local zoo!",
    "I named my dog Five Miles so I can tell people I walk Five Miles every single day!",
    "The pigeon strutted in like it paid rent, knocked over my coffee, and made direct eye contact the entire time!",
    "I put my phone on airplane mode but it's not flying anywhere. Worst purchase of my life, frankly!",
    "Parallel lines have so much in common. It's a shame they'll never meet!",
    "She asked for a stable relationship, so I bought a horse and moved into the barn. Communication is everything!",
    "I accidentally went to the wrong funeral and gave such a moving eulogy that they asked me back next week!",
    "My boss told me to have a good day, so I went home. Following orders. Model employee, honestly!",
    "I told the gym I wanted to lose ten pounds, and they said come back when you've lost the ten pounds!",
    "The recipe said 'set the oven to 180 degrees,' so now it faces the wall and won't talk to the fridge!",
    "My uncle once fought a vending machine over a stuck Twix and the vending machine won by a knockout!",
    "I'm on a seafood diet. I see food, and then I eat all of it immediately, like an animal!",
    "He whispered 'I love you' to the self-checkout machine because nobody else had said it back that week!",
    "I went to buy camouflage trousers but I couldn't find any. Greatest product they've ever made!",
    "The toddler negotiated bedtime like a hostage situation and, honestly, the toddler won!",
    "I asked the librarian if they had any books on paranoia. She whispered, 'They're right behind you!'",
    "My plan to become a beekeeper collapsed when I discovered I am terrified of tiny aggressive aircraft!",
    "Two muffins are in an oven. One says 'it's hot in here.' The other screams, 'A talking muffin!'",
    "I dressed as a vampire and the dentist gave me a discount, which is the only thing keeping me going!",
    "He answered every interview question with 'that's a great question' and then immediately fell silent!",
    "I joined a band called Missing Cat. You haven't seen us; we're on telephone poles all over town!",
    "My horoscope said I'd meet a tall dark stranger. Instead I tripped over the dog and apologized to a lamp!",
    "The dog learned to open the fridge and now negotiates for treats from a position of total strength!",
    "I bought a thesaurus and when I got home all the pages were blank. I have no words for my rage!",
    "She set one boundary and her family treated it like she'd personally declared war on the whole bloodline!",
    "I tried meditation but my brain spent the whole time reminding me of cringey things from 2007!",
    "The cat knocked the glass off the table while maintaining eye contact, then acted offended that I gasped!",
    "I told everyone I'd start running. I've run out of excuses, run out of time, and run out of the room!",
]

NEG = [
    "He slammed his fist on the table and roared, 'You lied to me, and now everything is ruined!'",
    "The storm tore the roof clean off and she screamed for the children over the howling wind!",
    "I read the diagnosis twice, then a third time, and felt the floor drop out from under me.",
    "'Don't you dare walk away from me!' she shouted, tears streaking down her furious face!",
    "The brakes failed on the mountain road and my whole life flashed before my eyes in an instant!",
    "He buried his father on a grey Tuesday and didn't speak a single word for the rest of the week.",
    "The soldiers advanced through the smoke as shells burst around them and the ground shook violently!",
    "'How could you betray us after everything we sacrificed?' he whispered, his voice shaking with rage.",
    "She clutched the letter to her chest and wept, knowing he was never, ever coming home again.",
    "The wolves circled closer in the dark, and I realized with cold horror that I was completely alone.",
    "'Get out! Get out of my house and never come back!' he bellowed, hurling the photograph at the wall!",
    "The doctor lowered her eyes and said quietly that there was nothing more anyone could do.",
    "Flames climbed the staircase as he screamed her name into the choking, blinding smoke!",
    "I stood at her grave in the rain, hollowed out, unable to believe she was truly gone.",
    "'You ruined my life, and I will never, ever forgive you for it!' she spat through clenched teeth.",
    "The earthquake split the street in two and people fled screaming as buildings crumbled around them!",
    "He read the eviction notice, sank to the kitchen floor, and put his head in his trembling hands.",
    "'Stop the car! Oh God, please, somebody stop the car!' she shrieked as the wheels left the road!",
    "The betrayal cut deeper than any wound, and a cold, quiet fury settled over him like a shroud.",
    "She watched the ship disappear over the horizon and understood she would never see him again.",
    "'I trusted you with everything, and you threw it all away!' he shouted, his fists shaking with anger.",
    "The fever climbed through the night and the mother sat helpless, praying her child would survive.",
    "Sirens wailed as the building collapsed, and the crowd surged back in a single terrified wave!",
    "He found the empty bottle, the unpaid bills, and the note, and his heart broke all over again.",
    "'How dare you stand there and lie to my face!' she screamed, slamming the door so hard it cracked!",
    "The avalanche thundered down the slope and swallowed the village whole in a matter of seconds!",
    "I held my grandmother's cold hand and felt something inside me quietly, permanently break.",
    "'You'll regret this for the rest of your miserable life!' he snarled, jabbing a finger at my chest.",
    "The plane dropped suddenly and the cabin filled with screams as oxygen masks crashed down!",
    "She stared at the divorce papers on the table and felt twenty years of her life turn to ash.",
    "'Run! Don't look back, just run!' he yelled, shoving me toward the door as the glass shattered!",
    "The verdict came back guilty and his mother's anguished cry echoed through the silent courtroom.",
    "Blood roared in my ears as the masked figure stepped out of the shadows and raised the knife!",
    "He lost the house, the job, and the family in a single catastrophic year, and simply stopped trying.",
    "'I hate you! I have always hated you!' the boy screamed, and then he was gone into the night!",
    "The icy water closed over her head and the world above shrank to a small, fading circle of light.",
    "He opened the telegram with shaking hands and read the three words that ended everything.",
    "'You did this! You did this to us!' she sobbed, pounding her fists against his unmoving chest!",
    "The fire alarm shrieked through the hospital as nurses rushed the beds toward the smoke-filled exit!",
    "I watched the tornado swallow the farmhouse and knew that nothing would ever be the same again.",
]
