"""Extra emotion corpora for the humor study, added on top of EmotionScope's
core 20 (which already include `surprised` and `curious`).

We add a HUMOR FAMILY — amused, playful, delighted, mirthful — plus `bored`
(a useful anti-humor contrast).  Each is written to be distinct:

  amused    — finding something funny / comic incongruity
  playful   — teasing, mischievous, light-hearted fun
  delighted — bright joyful pleasure / charmed
  mirthful  — overt merriment, giggling, laughing out loud
  bored     — tedium, monotony, nothing happening

`amused` lives in emotion_data.POS; the rest are here.  Valence/arousal are
metadata only (used for the circumplex viz), not for the vectors themselves.
"""

META = {
    "amused":    {"valence": 0.85, "arousal": 0.55},
    "playful":   {"valence": 0.80, "arousal": 0.60},
    "delighted": {"valence": 0.90, "arousal": 0.60},
    "mirthful":  {"valence": 0.85, "arousal": 0.70},
    "bored":     {"valence": -0.40, "arousal": -0.60},
}

TEMPLATES = {
    "playful": [
        "She snatched his hat, held it just out of reach, and danced backward across the lawn daring him to come and get it.",
        "He answered every serious question in a fake pirate voice just to see how long it would take before someone cracked.",
        "They turned the walk home into a competition over who could step on the most fallen leaves without admitting they were playing.",
        "She tiptoed up behind her brother, draped a sock over his head, and sprinted off before he could even turn around.",
        "We invented elaborate backstories for every stranger on the train and tried to keep straight faces the whole ride.",
        "He kept swapping the salt and sugar jars and waiting, with the patience of a cat, for someone to make tea.",
        "She booped his nose mid-argument just to derail him, and it absolutely worked, and she knew it would.",
        "The two of them narrated the dog's inner monologue in increasingly ridiculous accents until the dog left the room.",
        "He hid behind the door with a single balloon, planning the world's gentlest, silliest ambush.",
        "She challenged him to a thumb war to settle who got the last slice, then cheated outrageously and gloated.",
        "They built a fort out of couch cushions and defended it against an imaginary siege all afternoon.",
        "He wrote a tiny note saying 'you found it!' and hid it in the cereal box for whoever dug deepest.",
        "She kept poking him with a breadstick like a fencing foil, going en garde, until he surrendered laughing.",
        "We played the floor-is-lava across the entire living room and took it far too seriously for grown adults.",
        "He put googly eyes on everything in the fridge so the whole family would be quietly stared at by the leftovers.",
        "She teased him about his terrible parallel parking by narrating it like a tense sports broadcast.",
        "They had a staring contest that dissolved into giggles within four seconds, every single time, on purpose.",
        "He kept answering 'maybe' to everything in a sing-song voice just to be delightfully, harmlessly annoying.",
        "She drew a little moustache on her finger and held it up to everyone's face in the photo.",
        "We raced shopping trolleys down the empty aisle and pretended to be very serious Olympic athletes.",
        "He balanced a spoon on his nose at dinner and refused to acknowledge it, as if this were perfectly normal.",
        "She kept changing the lyrics of the song to be about the cat, and now nobody can remember the real words.",
        "They turned doing the dishes into a dramatic relay race with sound effects and a podium ceremony.",
        "He tickled the idea of a surprise, dangling hints all week just to watch everyone squirm with curiosity.",
        "She wore the oven mitts like boxing gloves and challenged the toaster to a duel at dawn.",
        "We made up a secret handshake so complicated that we both forgot it immediately and had to start over.",
        "He kept sneaking rubber ducks into her bag, one a day, never explaining, never confessing.",
        "She did an impression of him doing an impression of her, and it spiraled until neither could breathe.",
    ],
    "delighted": [
        "She opened the box and gasped with pure joy, pressing both hands to her cheeks at the tiny painted teacups inside.",
        "The first snow of the year began to fall and the children pressed their faces to the glass, glowing with happiness.",
        "He tasted the first strawberry of summer and closed his eyes, savoring it like the best thing in the world.",
        "When the puppy finally learned to sit, she clapped and beamed and scooped it up in a delighted hug.",
        "The whole table lit up when the cake arrived, candles flickering, everyone leaning in with shining faces.",
        "She found her grandmother's recipe in the old tin and her heart swelled with warm, bright joy.",
        "He stepped onto the balcony, saw the sea for the first time in years, and simply grinned at the horizon.",
        "The toddler discovered her own shadow and chased it around the garden shrieking with pure happiness.",
        "She unwrapped the gift slowly, then squealed and threw her arms around him when she saw what it was.",
        "The garden bloomed overnight and she wandered through it at dawn, charmed and utterly content.",
        "He heard the song from their wedding come on and pulled her up to dance right there in the kitchen, beaming.",
        "When the letter said she'd been accepted, she jumped up and down and hugged everyone in the room twice.",
        "The kitten batted the ribbon for the first time and the whole family melted, delighted by every clumsy pounce.",
        "She bit into the warm bread fresh from the oven and made a small, happy sound of complete satisfaction.",
        "The fireworks burst overhead and his face was lit up like a child's, full of wonder and glee.",
        "They reunited at the airport and she ran the last few steps, laughing and crying with sheer delight.",
        "He opened the curtains to a perfect blue morning and felt something bright and joyful rise in his chest.",
        "The baby laughed for the very first time and the entire room dissolved into delighted, helpless smiles.",
        "She spotted the double rainbow and called everyone outside, glowing, pointing, utterly thrilled.",
        "The chef set down the dessert and her eyes went wide with happy anticipation before she'd even tasted it.",
        "He found the exact book he'd been hunting for years, tucked on a dusty shelf, and hugged it to his chest.",
        "The class cheered when the experiment finally worked, and her face shone with proud, gleaming joy.",
        "She watched the lanterns rise into the night sky and felt her whole heart lift with them, delighted.",
        "The dog recognized him from across the park and sprinted over, and his laughter rang out with pure joy.",
        "They tasted the wine from the vineyard they'd dreamed of visiting and clinked glasses, glowing with happiness.",
        "She slipped on the new shoes, spun in front of the mirror, and beamed at her own reflection.",
        "The snow globe lit up when he shook it and the little girl's face filled with absolute wonder.",
        "He read the good news twice, then a grin spread slowly across his face until he was laughing with relief and joy.",
    ],
    "mirthful": [
        "The whole table erupted, wheezing and slapping the wood, until someone begged them all to please stop so they could breathe.",
        "She laughed so hard at his story that she slid off the chair and lay on the floor, helpless and gasping.",
        "He told the punchline and the room exploded into roaring, doubled-over, tears-streaming laughter.",
        "They got the giggles in the quiet library and the harder they tried to stop, the worse and louder it got.",
        "Grandpa's terrible pun set off a chain reaction of groans that collapsed into uncontrollable cackling.",
        "She snorted mid-laugh, which made everyone laugh harder, which made her snort again, and it never recovered.",
        "The comedian paused, raised one eyebrow, and the audience lost it, howling and stamping their feet.",
        "He was laughing so hard no sound came out, just a silent shaking and a hand desperately waving for mercy.",
        "The two of them dissolved into hysterics over a single word and could not, for the life of them, explain why.",
        "By the end of the joke half the room was crying with laughter and the other half had given up entirely.",
        "She clutched her stomach, breathless and red-faced, gasping that it hurt, it hurt, please stop.",
        "The kids were in absolute stitches, rolling around the carpet, shrieking with delighted laughter.",
        "His belly laugh was so contagious that strangers across the cafe started grinning and then chuckling too.",
        "They replayed the bloopers and the whole crew howled, wiping their eyes, replaying it again and again.",
        "The bridesmaid's speech had the entire reception roaring, banging the tables, helpless with mirth.",
        "She tried to read the message aloud three times and broke into giggles before she could finish a sentence.",
        "He did the impression again and the office erupted, people peeking over cubicles to catch the next round.",
        "The whole bus burst out laughing when the announcement glitched, and for a moment everyone was friends.",
        "They laughed until the candles guttered, until their cheeks ached, until nobody remembered what started it.",
        "Her cackle echoed down the hall and three coworkers wandered over just to be part of whatever was so funny.",
        "The dog did the thing again and the family collapsed, wheezing, clutching each other for support.",
        "He snorted his drink, which only made the table howl louder, which only made it worse, gloriously worse.",
        "The improv hit its peak and the crowd roared as one, a great warm wave of belly laughs rolling forward.",
        "She laughed so suddenly and so loudly at the meeting that she had to pretend it was a cough, badly.",
        "The whole row was shaking with suppressed giggles, shoulders bouncing, faces buried in their sleeves.",
        "By midnight the kitchen was full of laughter, the good kind, the kind that leaves your face sore in the morning.",
        "His one-liner landed and the bar exploded, glasses raised, strangers howling together at the punchline.",
        "They got laughing at the funeral, which was the worst possible time, which somehow made it ten times funnier.",
    ],
    "bored": [
        "He stared at the clock and watched the second hand crawl, certain it had slowed down just to torment him.",
        "The meeting droned on and on, the same slide for twenty minutes, and her mind drifted out the window and away.",
        "She refreshed the page for the ninth time, sighed, and went back to picking at the edge of the desk.",
        "Nothing happened. Then, for a long while, nothing continued to happen. He examined the ceiling tiles.",
        "The lecture was a flat grey hum, and he doodled spirals in the margin until the spirals filled the page.",
        "She had read the same sentence four times and absorbed none of it, the words sliding off like rain on glass.",
        "The waiting room offered one ancient magazine about boats, and he read it cover to cover, twice, in despair.",
        "Rain against the window, a clock ticking, the slow grey drip of an afternoon with absolutely nothing in it.",
        "He sighed, spun the empty chair, sighed again, and considered alphabetizing the stapler drawer for excitement.",
        "The film crawled through its second hour and she checked her phone, the time, her phone, the time, the time.",
        "The seminar speaker read every word off the slides in a monotone, and the room sank into a collective stupor.",
        "She traced the same crack in the ceiling for what felt like a geological age, waiting for the bell to ring.",
        "The queue inched forward by a single shuffling step every few minutes, and the minutes thickened into syrup.",
        "He tapped his pen, clicked it, tapped it, clicked it, until even the tapping became unbearably tedious.",
        "The train was delayed again and the platform announcement repeated the same dull apology for the eleventh time.",
        "Another grey commute, another identical corridor, another form to fill in fields she'd filled a hundred times.",
        "The documentary about soil drainage entered its fortieth minute and his eyes glazed into the middle distance.",
        "She counted the ceiling tiles, then the floor tiles, then started over, having forgotten the number already.",
        "The hold music looped for the twentieth time and he set the phone down and stared blankly at the wall.",
        "Nothing on, nothing to do, nothing to say; the afternoon stretched out flat and endless and beige.",
        "He reread the cereal box for the third morning running, having memorized the nutritional information by now.",
        "The professor's voice flattened into background noise and her notebook filled with the same idle box, redrawn.",
        "The road was straight and grey for a hundred identical miles and the radio only had the one droning station.",
        "She watched paint dry, almost literally, waiting for the wall to be touch-dry so the dull day could finally end.",
        "The spreadsheet scrolled on forever, row after identical row, and the numbers blurred into a tedious grey smear.",
        "He yawned, checked the time, found only four minutes had passed, and felt the afternoon settle over him like dust.",
        "The conference call was muted small talk and dead air, and she doodled until the doodles bored her too.",
        "Another rerun he'd seen a dozen times flickered on the screen while he lay there, listless, unbothered to change it.",
    ],
}
